---

name: Increment Release Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions: write-all

jobs:
  increment_release_version:
    name: Increment the release tag for this repo to trigger a rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Get next version
        uses: reecetech/version-increment@main
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Create a release
        uses: action-pack/github-release@v2
        with:
          tag: ${{ steps.version.outputs.version }}
          title: ${{ steps.version.outputs.version }}
          body: Patch increment rebuild to pull upstream changes.

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # use custom value instead of git tag
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
